version: '3.8'

services:
  bookings-api:
    build:
      context: .
      dockerfile: Bookings.Api/Dockerfile
    container_name: bookings-api
    networks:
      - proxy
    ports:
      - 7200:8080
      - 7300:8081
    depends_on:
      - bookings-db
      - bookings-rabbitMQ
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      Api_DB_USER: "${BOOKINGS_DB_USER}"
      Api_DB_PASSWORD: "${BOOKINGS_DB_PASSWORD}"
      Api_DB_HOST: "${MAIN_SERVER_ADDRESS}"
      Api_DB_PORT: "${BOOKINGS_DB_PORT}"
      Api_RabbitMq_Host: "${MAIN_SERVER_ADDRESS}"
      Api_RabbitMq_User: "${RABBITMQ_USER}"
      Api_RabbitMq_Password: "${RABBITMQ_PASSWORD}"
      
  bookings-hotels:
    build:
      context: .
      dockerfile: Bookings.Hotels/Dockerfile
    container_name: bookings-hotels
    networks:
      - proxy
    ports:
      - 7201:8080
      - 7301:8081
    depends_on:
      - bookings-db
      - bookings-rabbitMQ
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      Hotels_DB_USER: "${BOOKINGS_DB_USER}"
      Hotels_DB_PASSWORD: "${BOOKINGS_DB_PASSWORD}"
      Hotels_DB_HOST: "${MAIN_SERVER_ADDRESS}"
      Hotels_DB_PORT: "${BOOKINGS_DB_PORT}"
      Hotels_RabbitMq_Host: "${MAIN_SERVER_ADDRESS}"
      Hotels_RabbitMq_User: "${RABBITMQ_USER}"
      Hotels_RabbitMq_Password: "${RABBITMQ_PASSWORD}"

  bookings-db:
    restart: always
    image: mongo:6.0.7
    container_name: bookings-db
    command: --bind_ip_all
    volumes:
        - ./data/bookings-data:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: "${BOOKINGS_DB_USER}"
        MONGO_INITDB_ROOT_PASSWORD: "${BOOKINGS_DB_PASSWORD}"
    networks:
      - proxy
    ports:
      - 27017:27017

  bookings-rabbitMQ:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    container_name: bookings-rabbitmq
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD}"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    networks:
      - proxy
    ports:
      - 15673:15672
      - 5673:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq

volumes:
  bookings-data:
  
networks:
  proxy:
    driver: bridge